-- Vazio de propósito. O catálogo do chá (4 tamanhos de fralda e 23 mimos) entra
-- pela migration 20260911020000_family_catalog.sql, que vale em todos os ambientes.
-- Duplicar a lista aqui criaria duas fontes para a mesma decisão de produto.
-- Os testes criam e removem seus próprios dados fictícios.
